### ISSUE TITLE
artisan route:list gives an error

### ISSUE THREAD

**Issue by rafailml** [dialect-katrineholm/laravel-gdpr-compliance#36]
When I run php artisan route:list  , I'm getting an error:
 ReflectionException  : Class Dialect\Gdpr\Http\Controllers\GdprController does not exist

**Comment by rafailml** [comment]
You'll need to edit vendor/dialect/laravel-gdpr-compliance/src/GdprServiceProvider.php line 35.
Change to:
`'namespace' => 'App\Http\Controllers',`

**Comment by KristofferTennivaara** [comment]
Thank you, this is now fixed.

Problem is, either the tests work, or the published controller gets the right namespace.
