### ISSUE TITLE
Shouldn't assume standard app:name

### ISSUE THREAD

**Issue by DanielRTRD** [dialect-katrineholm/laravel-gdpr-compliance#47]
https://github.com/dialect-katrineholm/laravel-gdpr-compliance/blob/master/src/GdprServiceProvider.php#L39

This cannot be assumed to be the standard name.

**Comment by KristofferTennivaara** [comment]
Thank you for noticing this, it has indeed been assumed to be the standard name. 
Will merge your PR.
