### ISSUE TITLE
AnonymizeInactiveUsers-command fails when non-default app:name i set

### ISSUE THREAD

**Issue by DanielRTRD** [dialect-katrineholm/laravel-gdpr-compliance#58]
<img width="836" alt="screenshot 2018-11-13 at 07 18 26" src="https://user-images.githubusercontent.com/9788214/48394629-8a45ea00-e714-11e8-8226-8fb5afbc800a.png">

**Comment by DanielRTRD** [comment]
@KristofferTennivaara Can you take a look at this?

**Comment by KristofferTennivaara** [comment]
Sorry for the delay @DanielRTRD.
I see, it assumes that the default name is 'App' and that the model is 'User'.
Making this work for all cases is ideal, I will take a look at your fix, thank you.
