### ISSUE TITLE
Running gdpr:anonymizeInactiveUsers does not set isAnonymized

### ISSUE THREAD

**Issue by DanielRTRD** [dialect-katrineholm/laravel-gdpr-compliance#60]
Only the controller does this:
```
$user->update([
      'isAnonymized' => true,
]);
```

**Comment by DanielRTRD** [comment]
@KristofferTennivaara Can you take a look at this?

**Comment by KristofferTennivaara** [comment]
Just noticed the problem in one of our apps, I will merge your PR @DanielRTRD, thank you.
