### ISSUE TITLE
README instructions contain a typo

### ISSUE THREAD

**Issue by carlos-ballester** [dialect-katrineholm/laravel-gdpr-compliance#64]
In the README file, it is stated that 

Using getAnonynomized{column} to return anonymizable data

public function getAnonynomizedEmail()
    {
        return 'your_return_value';
    }

There is a typo in getAnony**NO**mized{column}, it should be getAnonymized{column} for it to work

Just in case anyone ran into it not working properly and didn't know why

**Comment by stromgren** [comment]
Thank you for bringing this to our attention! I submitted a PR, expect it to be merged on a couple of hours.
