### ISSUE TITLE
Suggestion: change boolean 'isAnonymized' to datetime-field 'anonymized_at'

### ISSUE THREAD

**Issue by KarlHalonen** [dialect-katrineholm/laravel-gdpr-compliance#66]
Changing boolean 'isAnonymized' to datetime-field 'anonymized_at' would be more in line with laravel convention.

**Comment by KristofferTennivaara** [comment]
this would be a breaking change for all projects using this lib.

**Comment by DanielRTRD** [comment]
Even though it is breaking projects, I think this would be a good change.
